# Generated by Django 3.1.7 on 2024-05-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('student', 'STUDENT'), ('coordinator', 'COORDINATOR'), ('supervisor', 'SUPERVISOR'), ('admin', 'ADMIN')], max_length=100)),
                ('manage_users', models.BooleanField(default=False)),
                ('submit_tasks', models.BooleanField(default=False)),
                ('add_field_place', models.BooleanField(default=False)),
                ('view_field_place', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'User authorization',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('Fr', 'French')], default='en-us', max_length=5),
        ),
    ]
