# Generated by Django 3.1.7 on 2024-05-11 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 11, 19, 57, 37, 875793, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 11, 19, 57, 37, 875793, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requests',
            name='requested_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 11, 19, 57, 37, 875793, tzinfo=utc)),
        ),
    ]
