# Generated by Django 3.2.4 on 2024-06-21 09:04

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_auto_20240511_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 9, 4, 49, 281807, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requests',
            name='requested_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
